# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='テスト名')),
                ('test_info', models.TextField(verbose_name='テスト範囲')),
                ('jugyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_day', to='jugyo.Jugyo', verbose_name='授業')),
            ],
        ),
    ]
