# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0002_testday'),
    ]

    operations = [
        migrations.AddField(
            model_name='testday',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 5, 31, 6, 54, 31, 909440, tzinfo=utc), verbose_name='テスト日'),
            preserve_default=False,
        ),
    ]
