# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0003_testday_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoJugyoDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(verbose_name='休講日')),
                ('jugyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugyo_day', to='jugyo.Jugyo', verbose_name='授業')),
            ],
        ),
    ]
