# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0004_nojugyoday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dead_line', models.DateField(verbose_name='締め切り')),
                ('info', models.TextField(verbose_name='課題内容')),
                ('jugyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='jugyo.Jugyo', verbose_name='授業')),
            ],
        ),
    ]
