# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0008_auto_20160604_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpJugyo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(verbose_name='補講日')),
                ('jugyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_jugyo', to='jugyo.Jugyo', verbose_name='授業')),
            ],
        ),
        migrations.AlterField(
            model_name='nojugyo',
            name='jugyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_jugyo', to='jugyo.Jugyo', verbose_name='授業'),
        ),
    ]
