# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0011_auto_20160604_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='jugyos',
            field=models.ManyToManyField(related_name='teachers', to='jugyo.Jugyo', verbose_name='jugyo'),
        ),
    ]
