# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0014_jugyodatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='コメント')),
                ('jugyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jugyo.Jugyo', verbose_name='授業')),
            ],
        ),
    ]
