# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0017_auto_20160604_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='jugyo',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
