# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0020_mypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='jugyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='jugyo.Jugyo', verbose_name='授業'),
        ),
    ]
