# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0021_auto_20160605_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='jugyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='jugyo.Jugyo', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='jugyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='jugyo.Jugyo', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='jugyodatetime',
            name='jugyos',
            field=models.ManyToManyField(related_name='date_times', to='jugyo.Jugyo', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='nojugyo',
            name='jugyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_jugyos', to='jugyo.Jugyo', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='upjugyo',
            name='jugyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_jugyos', to='jugyo.Jugyo', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='year',
            name='jugyo',
            field=models.ManyToManyField(related_name='years', to='jugyo.Jugyo', verbose_name='授業'),
        ),
    ]
