# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jugyo', '0022_auto_20160607_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 6, 25, 10, 49, 42, 128507, tzinfo=utc), max_length=255, verbose_name='課題名'),
            preserve_default=False,
        ),
    ]
